name: Manual
on:
  workflow_dispatch: # 手動トリガー
    inputs:
      greeting: # 入力パラメータ名
        type: string # データ型
        default: Hello # 入力パラメータのデフォルト値
        required: true # 入力パラメータの必須フラグ
        description: A cheerful word # 入力パラメータの概要
      log-level:
        type: choice
        options:
          - info
          - warn
          - error
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ inputs.greeting }}" # 入力パラメータ「greeting」の参照
      - run: echo "Log level is ${{ inputs['log-level'] }}" # 入力パラメータ「log-level」の参照
